- id: cpplint
  name: cpplint
  description: Check C/C++ files for style issues following Google's C++ style guide
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: cpplint
